### ISSUE TITLE
Build & Test Instructions

### ISSUE THREAD

**Issue by praveenpuglia** [dhavalpzala/multi-hashmap#3]
I see the module usage instructions but couldn't find any build instructions and how to run tests. Can we add that as  Building.md or something similar?

**Comment by dhavalpzala** [comment]
We can add developer.md which includes all the instructions related to development. what say @praveenpuglia ?

**Comment by praveenpuglia** [comment]
Sure. You can do that. I'll be on #2 PR :)

**Comment by dhavalpzala** [comment]
Okay. I will add that.

**Comment by dhavalpzala** [comment]
Added DEVELOPMENT.md
